version: '3'
services:
  eureka-server:
    image: cike/eureka-server
    container_name: sc-eureka-server
    restart: always
    volumes:
      - ./data/eureka-server/logs:/var/logs
      - ./data/pinpoint-agent:/pinpoint-agent
    networks:
      - sc-net
    ports:
      - 8761:8761
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USERNAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - JAVA_OPTS=-javaagent:${PINPOINT_AGENT_JAR} -Dpinpoint.agentId=eureka-server1 -Dpinpoint.applicationName=eureka-server
    depends_on:
      - rabbitmq

  gateway:
    image: cike/gateway-web
    container_name: sc-gateway-web
    restart: always
    volumes:
      - ./data/gateway-web/logs:/var/logs
      - ./data/pinpoint-agent:/pinpoint-agent
    networks:
      - sc-net
    ports:
      - 8443:8443
    env_file: .env
    environment:
      - JAVA_OPTS=-javaagent:${PINPOINT_AGENT_JAR} -Dpinpoint.agentId=gateway-web1 -Dpinpoint.applicationName=gateway-web
    depends_on:
      - eureka-server
      - authorization-server
      - authentication-server

  gateway-admin:
    image: cike/gateway-admin
    container_name: sc-gateway-web
    restart: always
    volumes:
      - ./data/gateway-admin/logs:/var/logs
      - ./data/pinpoint-agent:/pinpoint-agent
    networks:
      - sc-net
    ports:
      - 8445:8445
    env_file: .env
    environment:
      - JAVA_OPTS=-javaagent:${PINPOINT_AGENT_JAR} -Dpinpoint.agentId=gateway-admin1 -Dpinpoint.applicationName=gateway-admin
    depends_on:
      - eureka-server
      - authorization-server
      - authentication-server

  authorization-server:
    image: cike/authorization-server
    container_name: sc-authorization-server
    restart: always
    volumes:
      - ./data/authorization-server/logs:/var/logs
      - ./data/pinpoint-agent:/pinpoint-agent
    networks:
      - sc-net
    ports:
      - 8000:8000
    env_file: .env
    environment:
      - JAVA_OPTS=-javaagent:${PINPOINT_AGENT_JAR} -Dpinpoint.agentId=authorization-server1 -Dpinpoint.applicationName=authorization-server
    depends_on:
      - eureka-server
      - postgres

  authentication-server:
    image: cike/authentication-server
    container_name: sc-authentication-server
    restart: always
    volumes:
      - ./data/authentication-server/logs:/var/logs
      - ./data/pinpoint-agent:/pinpoint-agent
    networks:
      - sc-net
    ports:
      - 8001:8001
    env_file: .env
    environment:
      - JAVA_OPTS=-javaagent:${PINPOINT_AGENT_JAR} -Dpinpoint.agentId=authentication-server1 -Dpinpoint.applicationName=authentication-server
    depends_on:
      - eureka-server
      - postgres